import { useEffect, useMemo, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import axios from 'axios'

type Layer = { id: string; name: string; selected: boolean }
type Asset = { path: string; layer: string; size: number; archived: boolean }
type Listing = { layers: Layer[]; assets: Asset[]; packActive: boolean; subpackConfigured: boolean }
type Preview = { count: number; edits: number; changes: string[]; warnings: string[] }
type Change = { action: 'archive' | 'restore'; paths: string[] }
const api = axios.create({ baseURL: '/api' })
const errorText = (error: unknown) => axios.isAxiosError(error) ? error.response?.data?.error || error.message : String(error)
const managed = new Set(['manifest.json', 'pack_icon.png', 'blocks.json', 'textures/terrain_texture.json', 'textures/flipbook_textures.json', 'textures/flipbook_texture.json', 'textures/textures_list.json'])
const isImage = (path: string) => /\.(png|tga|jpe?g|gif|webp)$/i.test(path)
const folderOf = (path: string) => path.includes('/') ? path.split('/')[0] : '(root)'
const nameOf = (path: string) => path.split('/').pop() || path
const sizeOf = (size: number) => size < 1024 ? `${size} B` : `${(size / 1024).toFixed(1)} KB`
const pageSize = 48

export default function PackAssets({ server, folder, stopped }: { server: string; folder: string; stopped: boolean }) {
  const url = `/pack-assets/${encodeURIComponent(server)}/resource/${encodeURIComponent(folder)}`
  const qc = useQueryClient()
  const listing = useQuery({ queryKey: ['pack-assets', server, folder], queryFn: async () => (await api.get<Listing>(url)).data })
  const [layer, setLayer] = useState('main')
  const [query, setQuery] = useState('')
  const [state, setState] = useState<'all' | 'present' | 'archived'>('all')
  const [folderFilter, setFolderFilter] = useState('all')
  const [section, setSection] = useState<'images' | 'other'>('images')
  const [page, setPage] = useState(1)
  const resultsRef = useRef<HTMLDivElement>(null)
  const [selected, setSelected] = useState<string[]>([])
  const [focused, setFocused] = useState<Asset | null>(null)
  const [pending, setPending] = useState<{ request: Change; preview: Preview } | null>(null)
  const [notice, setNotice] = useState('')
  const inspect = useMutation({ mutationFn: async (request: Change) => ({ request, preview: (await api.post<Preview>(url, { ...request, layer, preview: true })).data }), onSuccess: result => setPending(result) })
  const change = useMutation({ mutationFn: async (request: Change) => (await api.post(url, { ...request, layer })).data, onSuccess: async () => { setNotice('Assets updated. Restart the server to apply changes.'); setSelected([]); setPending(null); await qc.invalidateQueries({ queryKey: ['pack-assets', server, folder] }) } })
  const layerAssets = useMemo(() => (listing.data?.assets || []).filter(asset => asset.layer === layer), [listing.data, layer])
  const folders = useMemo(() => [...new Set(layerAssets.map(asset => folderOf(asset.path)))].sort(), [layerAssets])
  const assets = useMemo(() => layerAssets.filter(asset => isImage(asset.path) === (section === 'images') && (state === 'all' || (state === 'archived') === asset.archived) && (folderFilter === 'all' || folderOf(asset.path) === folderFilter) && asset.path.toLowerCase().includes(query.toLowerCase())), [layerAssets, section, state, folderFilter, query])
  useEffect(() => setPage(1), [layer, section, state, folderFilter, query])
  const pageCount = Math.max(1, Math.ceil(assets.length / pageSize))
  const currentPage = Math.min(page, pageCount)
  const pageAssets = assets.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  const selectedAssets = layerAssets.filter(asset => selected.includes(asset.path))
  const allArchived = selectedAssets.length > 0 && selectedAssets.every(asset => asset.archived)
  const allPresent = selectedAssets.length > 0 && selectedAssets.every(asset => !asset.archived)
  const imageUrl = (asset: Asset) => `/api${url}?content=1&layer=${encodeURIComponent(asset.layer)}&path=${encodeURIComponent(asset.path)}`
  const fallback = layer === 'main' ? 'When disabled, a lower-priority pack or Minecraft’s default asset can show through if it provides the same path.' : 'When disabled, the same path in the main pack, another pack, or Minecraft’s default assets can show through.'
  const inspectOne = (asset: Asset) => { setSelected([asset.path]); setPending(null); inspect.mutate({ action: asset.archived ? 'restore' : 'archive', paths: [asset.path] }) }
  const switchLayer = (next: string) => { setLayer(next); setSelected([]); setPending(null); setFocused(null); setFolderFilter('all') }
  const toggle = (path: string) => { setPending(null); setSelected(current => current.includes(path) ? current.filter(item => item !== path) : [...current, path]) }
  const goToPage = (next: number) => { setPage(next); resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
  return <section className="panel pack-assets">
    <div className="pack-assets-heading"><div><p className="kicker">PACK CONTENT</p><h2>Asset explorer</h2><p className="muted">Choose which textures this pack contributes. Disabled files are kept for restoration.</p></div><span>{layerAssets.length} files</span></div>
    {listing.isLoading && <p className="muted">Loading assets…</p>}{listing.isError && <p className="error" role="alert">{errorText(listing.error)}</p>}
    {listing.data && <>
      <div className="pack-assets-topbar"><label>Pack layer<select value={layer} onChange={event => switchLayer(event.target.value)}>{listing.data.layers.map(item => <option key={item.id} value={item.id}>{item.name}{item.selected ? ' · selected by world' : ''}</option>)}</select></label><label className="pack-assets-search"><span aria-hidden="true">⌕</span><input type="search" aria-label="Search assets" placeholder="Search names or paths" value={query} onChange={event => setQuery(event.target.value)} />{query && <button type="button" aria-label="Clear search" onClick={() => setQuery('')}>×</button>}</label></div>
      <div className="pack-assets-sections" role="group" aria-label="Asset type"><button type="button" className={section === 'images' ? 'active' : ''} onClick={() => { setSection('images'); setSelected([]); setPending(null) }}>Images <span>{layerAssets.filter(asset => isImage(asset.path)).length}</span></button><button type="button" className={section === 'other' ? 'active' : ''} onClick={() => { setSection('other'); setSelected([]); setPending(null) }}>Other files <span>{layerAssets.filter(asset => !isImage(asset.path)).length}</span></button></div>
      <div className="pack-assets-filters"><label>Folder<select value={folderFilter} onChange={event => setFolderFilter(event.target.value)}><option value="all">All folders</option>{folders.map(item => <option key={item} value={item}>{item}</option>)}</select></label><label>Status<select value={state} onChange={event => setState(event.target.value as typeof state)}><option value="all">All states</option><option value="present">Contributing</option><option value="archived">Disabled</option></select></label><span>{assets.length ? `${(currentPage - 1) * pageSize + 1}–${Math.min(currentPage * pageSize, assets.length)} of ${assets.length}` : '0 results'}</span></div>
      <p className="muted pack-assets-layer">{layer === 'main' ? 'Main pack · used by every subpack.' : !listing.data.packActive ? 'This pack is not active in the world.' : !listing.data.subpackConfigured ? 'No subpack is explicitly saved in the world JSON; Minecraft chooses automatically.' : listing.data.layers.find(item => item.id === layer)?.selected ? 'This subpack is explicitly selected by the world.' : 'A different subpack is explicitly selected by the world.'} {fallback}</p>
      {selected.length > 0 && <div className="pack-assets-selection"><strong>{selected.length} selected</strong><button type="button" className="secondary-action" onClick={() => { setSelected([]); setPending(null) }}>Clear</button><button type="button" className="primary" disabled={!stopped || inspect.isPending || (!allArchived && !allPresent)} onClick={() => inspect.mutate({ action: allArchived ? 'restore' : 'archive', paths: selected })}>{inspect.isPending ? 'Checking…' : allArchived ? 'Restore selected…' : 'Disable selected…'}</button>{!allArchived && !allPresent && <small>Select files with the same state.</small>}</div>}
      {!stopped && <p className="muted">Stop the server to change assets.</p>}{inspect.isError && <p className="error" role="alert">{errorText(inspect.error)}</p>}{change.isError && <p className="error" role="alert">{errorText(change.error)}</p>}{notice && <p className="notice" role="status">{notice}</p>}
      {section === 'images' ? <div ref={resultsRef} className="pack-assets-grid">{pageAssets.map(asset => <article className={`pack-asset-card ${asset.archived ? 'is-archived' : ''} ${selected.includes(asset.path) ? 'is-selected' : ''}`} key={asset.path}><button className="pack-asset-image" type="button" onClick={() => setFocused(asset)} aria-label={`View ${asset.path}`}><img src={imageUrl(asset)} alt="" loading="lazy" /><span className="pack-asset-zoom" aria-hidden="true">↗</span></button><div className="pack-asset-card-content"><strong title={asset.path}>{nameOf(asset.path)}</strong><small title={asset.path}>{asset.path}</small><div className="pack-asset-card-foot"><span className={asset.archived ? 'pack-asset-archived' : 'pack-asset-present'}>{asset.archived ? 'Disabled' : 'Contributing'}</span><span>{sizeOf(asset.size)}</span></div><div className="pack-asset-card-actions"><button type="button" disabled={!stopped} onClick={() => inspectOne(asset)}>{asset.archived ? 'Restore' : 'Disable'}</button><button type="button" className={selected.includes(asset.path) ? 'selected' : ''} onClick={() => toggle(asset.path)} aria-label={`${selected.includes(asset.path) ? 'Deselect' : 'Select'} ${asset.path}`}>{selected.includes(asset.path) ? '✓ Selected' : 'Select'}</button></div></div></article>)}{assets.length === 0 && <p className="muted">No images match these filters.</p>}</div> : <div ref={resultsRef} className="pack-assets-other">{pageAssets.map(asset => <article className="pack-asset-other-row" key={asset.path}><span className="pack-asset-type">{asset.path.split('.').pop()?.slice(0, 5).toUpperCase()}</span><div><strong>{nameOf(asset.path)}</strong><small>{asset.path}</small></div><span className={asset.archived ? 'pack-asset-archived' : 'pack-asset-present'}>{asset.archived ? 'Disabled' : 'Contributing'}</span><button type="button" disabled={!stopped || managed.has(asset.path)} onClick={() => inspectOne(asset)}>{managed.has(asset.path) ? 'Managed' : asset.archived ? 'Restore' : 'Disable'}</button></article>)}{assets.length === 0 && <p className="muted">No other files match these filters.</p>}</div>}
      {pageCount > 1 && <nav className="pack-assets-pagination" aria-label="Asset pages"><button type="button" disabled={currentPage === 1} onClick={() => goToPage(1)} aria-label="First page">«</button><button type="button" disabled={currentPage === 1} onClick={() => goToPage(currentPage - 1)}>Previous</button><span>Page {currentPage} of {pageCount}</span><button type="button" disabled={currentPage === pageCount} onClick={() => goToPage(currentPage + 1)}>Next</button><button type="button" disabled={currentPage === pageCount} onClick={() => goToPage(pageCount)} aria-label="Last page">»</button></nav>}
    </>}
    {focused && <div className="files-dialog-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setFocused(null) }}><section className="pack-asset-detail panel" role="dialog" aria-modal="true" aria-label={`Preview ${focused.path}`}><header><div><h3>{nameOf(focused.path)}</h3><p>{focused.path} · {sizeOf(focused.size)}</p></div><button type="button" className="secondary-action" onClick={() => setFocused(null)} aria-label="Close preview">×</button></header><div className="pack-asset-detail-image"><img src={imageUrl(focused)} alt={nameOf(focused.path)} /></div><footer><span>{focused.archived ? 'Disabled in this layer' : 'Contributing from this layer'}</span><button type="button" className="primary" disabled={!stopped} onClick={() => { inspectOne(focused); setFocused(null) }}>{focused.archived ? 'Restore…' : 'Disable…'}</button></footer></section></div>}
    {pending && <div className="files-dialog-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setPending(null) }}><section className="pack-asset-confirm panel" role="dialog" aria-modal="true" aria-label="Confirm asset changes"><h3>{pending.request.action === 'archive' ? 'Disable' : 'Restore'} {pending.preview.count} asset{pending.preview.count === 1 ? '' : 's'}?</h3><p>{pending.request.action === 'archive' ? fallback : 'These files will contribute again after a server restart.'}</p><p>{pending.preview.edits} JSON catalog file{pending.preview.edits === 1 ? '' : 's'} will be updated.</p>{pending.preview.changes.map((item, index) => <small key={`${item}-${index}`}>{item}</small>)}{pending.preview.warnings.map(item => <small key={item}>Review: {item}</small>)}<div><button type="button" className="secondary-action" onClick={() => setPending(null)}>Cancel</button><button type="button" className="primary" disabled={change.isPending} onClick={() => change.mutate(pending.request)}>{change.isPending ? 'Applying…' : pending.request.action === 'archive' ? 'Disable assets' : 'Restore assets'}</button></div></section></div>}
  </section>
}
